Qimo/MAIN/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("MENU.urls")),
    #path("kitchen/", include("KITCHEN.urls")),
    #path("pay/", include("PAY.urls")),
]

Qimo/MENU/urls.py
from django.urls import path
from . import views

app_name="MENU"

urlpatterns = [
    path("", views.index, name="index"),
]

Qimo/KITCHEN/models.py
from django.db import models

# Create your models here.

Qimo/MDESK/models.py
from django.db import models

# Create your models here.

Qimo/MENU/models.py
from django.db import models

# Create your models here.

Qimo/PAY/models.py
from django.db import models

# Create your models here.

Qimo/KITCHEN/views.py
from django.shortcuts import render

# Create your views here.

Qimo/MDESK/views.py
from django.shortcuts import render

# Create your views here.

Qimo/MENU/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

# Create your views here.
def index(request):
    return render(request, "MENU/index.html")

Qimo/PAY/views.py
from django.shortcuts import render

# Create your views here.

Qimo/MENU/templates/MENU/index.html
{% extends "base.html" %}

{% block Title %}
    <title>Qimo Menü</title>
{% endblock Title %}

{% block BODY %}
    {% include "navbar.html" %}
{% endblock BODY %}

Qimo/templates/base.html
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      {% block Title %}
            <title>Home</title>
      {% endblock Title %}
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      {% block CSS %}

      {% endblock CSS %}
</head>
<body>
      {% block BODY %}

      {% endblock BODY %}


      {% block JS %}
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
      {% endblock JS %}
</body>
</html>

Qimo/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'MENU:index' %}">Qimo</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Account
              </a>
              {% comment %} <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'USERAPP:profile' %}">Profile</a></li>
                  <li><hr class="dropdown-divider"></li>
                  {% if user.is_authenticated %}
                  <li><a class="dropdown-item" href="{% url 'USERAPP:logout' %}">Logout</a></li>
                  {% else %}
                  <li><a class="dropdown-item" href="{% url 'USERAPP:login' %}">Login</a></li>
                  <li><a class="dropdown-item" href="{% url 'USERAPP:register' %}">Register</a></li>
                  {% endif %}
              </ul> {% endcomment %}
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="keyword">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>